// Generated by gencpp from file mrobot_simple_nav_msgs/sys_state.msg
// DO NOT EDIT!


#ifndef MROBOT_SIMPLE_NAV_MSGS_MESSAGE_SYS_STATE_H
#define MROBOT_SIMPLE_NAV_MSGS_MESSAGE_SYS_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrobot_simple_nav_msgs
{
template <class ContainerAllocator>
struct sys_state_
{
  typedef sys_state_<ContainerAllocator> Type;

  sys_state_()
    : state(false)  {
    }
  sys_state_(const ContainerAllocator& _alloc)
    : state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> const> ConstPtr;

}; // struct sys_state_

typedef ::mrobot_simple_nav_msgs::sys_state_<std::allocator<void> > sys_state;

typedef boost::shared_ptr< ::mrobot_simple_nav_msgs::sys_state > sys_statePtr;
typedef boost::shared_ptr< ::mrobot_simple_nav_msgs::sys_state const> sys_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator1> & lhs, const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator1> & lhs, const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrobot_simple_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrobot_simple_nav_msgs/sys_state";
  }

  static const char* value(const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n"
;
  }

  static const char* value(const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sys_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrobot_simple_nav_msgs::sys_state_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MROBOT_SIMPLE_NAV_MSGS_MESSAGE_SYS_STATE_H
