// Generated by gencpp from file line_follower_turtlebot/sound.msg
// DO NOT EDIT!


#ifndef LINE_FOLLOWER_TURTLEBOT_MESSAGE_SOUND_H
#define LINE_FOLLOWER_TURTLEBOT_MESSAGE_SOUND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace line_follower_turtlebot
{
template <class ContainerAllocator>
struct sound_
{
  typedef sound_<ContainerAllocator> Type;

  sound_()
    : word()  {
    }
  sound_(const ContainerAllocator& _alloc)
    : word(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _word_type;
  _word_type word;





  typedef boost::shared_ptr< ::line_follower_turtlebot::sound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_follower_turtlebot::sound_<ContainerAllocator> const> ConstPtr;

}; // struct sound_

typedef ::line_follower_turtlebot::sound_<std::allocator<void> > sound;

typedef boost::shared_ptr< ::line_follower_turtlebot::sound > soundPtr;
typedef boost::shared_ptr< ::line_follower_turtlebot::sound const> soundConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_follower_turtlebot::sound_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_follower_turtlebot::sound_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_follower_turtlebot::sound_<ContainerAllocator1> & lhs, const ::line_follower_turtlebot::sound_<ContainerAllocator2> & rhs)
{
  return lhs.word == rhs.word;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_follower_turtlebot::sound_<ContainerAllocator1> & lhs, const ::line_follower_turtlebot::sound_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_follower_turtlebot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::line_follower_turtlebot::sound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_follower_turtlebot::sound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_follower_turtlebot::sound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_follower_turtlebot::sound_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_follower_turtlebot::sound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_follower_turtlebot::sound_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_follower_turtlebot::sound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf5cbdd7f0c6b9eaa898f882ab6eade6";
  }

  static const char* value(const ::line_follower_turtlebot::sound_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf5cbdd7f0c6b9eaULL;
  static const uint64_t static_value2 = 0xa898f882ab6eade6ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_follower_turtlebot::sound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_follower_turtlebot/sound";
  }

  static const char* value(const ::line_follower_turtlebot::sound_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_follower_turtlebot::sound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string word\n"
;
  }

  static const char* value(const ::line_follower_turtlebot::sound_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_follower_turtlebot::sound_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.word);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sound_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_follower_turtlebot::sound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_follower_turtlebot::sound_<ContainerAllocator>& v)
  {
    s << indent << "word: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.word);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_FOLLOWER_TURTLEBOT_MESSAGE_SOUND_H
